namespace LearnCSharp.Practice
{
    internal class Comment
    {
        //Single line comment...

        /*
         Multi line comment...
         Multi line comment...
         Multi line comment...
         Multi line comment...
         */

        /*
         * Multi line comment...
         * Multi line comment...
         * Multi line comment...
         * Multi line comment...
         */
    }
}
